name:                bf-hs
version:             0.1.0.0
github:              "CyberGsus/brainfuck-lab"
license:             MIT
author:              "Cyber Gsus"
maintainer:          "cyber.gsuscode@gmail.com"
copyright:           "2021 Cyber Gsus"


# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/CyberGsus/brainfuck-lab#readme>

dependencies:
- base >= 4.7 && < 5
- mtl
- transformers
- bytestring

library:
  source-dirs: src

executables:
  bf-hs-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bf-hs

tests:
  bf-hs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bf-hs
